//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComidaService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class activity
    {
        public activity()
        {
            this.useractivity = new HashSet<useractivity>();
        }
    
        public int ID { get; set; }
        public string Type { get; set; }
        public Nullable<double> CalorieBurnPrMin { get; set; }
    
        public virtual ICollection<useractivity> useractivity { get; set; }
    }
}
