//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComidaService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class compname
    {
        public int CompId { get; set; }
        public string SrtOrd { get; set; }
        public string Unit { get; set; }
        public string CmpNamDK { get; set; }
        public string CmpNamEN { get; set; }
        public string PublStatus { get; set; }
        public string EurofoodsTag { get; set; }
    }
}
