//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComidaService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class foodinfo
    {
        public foodinfo()
        {
            this.userintake = new HashSet<userintake>();
            this.shoppinglistitem = new HashSet<shoppinglistitem>();
            this.recepeitem = new HashSet<recepeitem>();
            this.foodstoreitem = new HashSet<foodstoreitem>();
        }
    
        public int FoodId { get; set; }
        public string DanName { get; set; }
        public string ProdName { get; set; }
        public string EngName { get; set; }
        public string SysName { get; set; }
        public string MainGrp { get; set; }
        public string SubGrp { get; set; }
        public string Waste { get; set; }
        public string NCF { get; set; }
        public string FACF { get; set; }
        public string PEF { get; set; }
        public string FEF { get; set; }
        public string CEF { get; set; }
        public string Density { get; set; }
        public string Remarks { get; set; }
        public string PublStatus { get; set; }
        public string LanguaL { get; set; }
        public string GRIN { get; set; }
        public string FISHBASE { get; set; }
        public string BASIS { get; set; }
        public string USDA { get; set; }
        public string FIFood { get; set; }
        public string UKFood { get; set; }
        public string FRFood { get; set; }
        public string DEFood { get; set; }
        public string SEFood { get; set; }
        public string NOFood { get; set; }
        public string NLFood { get; set; }
        public string ISFood { get; set; }
        public string SPFood { get; set; }
        public string ITFood { get; set; }
        public string DateUpdated { get; set; }
        public string UpdatedBy { get; set; }
        public string Recipe { get; set; }
        public string WaterYield { get; set; }
        public string FatYield { get; set; }
    
        public virtual ICollection<userintake> userintake { get; set; }
        public virtual ICollection<shoppinglistitem> shoppinglistitem { get; set; }
        public virtual ICollection<recepeitem> recepeitem { get; set; }
        public virtual ICollection<foodstoreitem> foodstoreitem { get; set; }
    }
}
