//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComidaService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class recepe
    {
        public recepe()
        {
            this.favoriterecepe = new HashSet<favoriterecepe>();
            this.foodplanrecepe = new HashSet<foodplanrecepe>();
            this.recepecomments = new HashSet<recepecomments>();
            this.recepestep = new HashSet<recepestep>();
            this.recepeitem = new HashSet<recepeitem>();
        }
    
        public int ID { get; set; }
        public int Owner { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<int> Rating { get; set; }
        public Nullable<bool> Published { get; set; }
        public int Details { get; set; }
    
        public virtual ICollection<favoriterecepe> favoriterecepe { get; set; }
        public virtual ICollection<foodplanrecepe> foodplanrecepe { get; set; }
        public virtual user user { get; set; }
        public virtual ICollection<recepecomments> recepecomments { get; set; }
        public virtual ICollection<recepestep> recepestep { get; set; }
        public virtual ICollection<recepeitem> recepeitem { get; set; }
    }
}
