//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComidaService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class references
    {
        public string RefId { get; set; }
        public string PubTypeId { get; set; }
        public string AcqTypeId { get; set; }
        public string Title { get; set; }
        public string Authors { get; set; }
        public string Publishr { get; set; }
        public string PubDate { get; set; }
        public string Version { get; set; }
        public string OrigLang { get; set; }
        public string Languages { get; set; }
        public string ISBN { get; set; }
        public string FstEdDat { get; set; }
        public string EdNo { get; set; }
        public string NoPages { get; set; }
        public string BkTitle { get; set; }
        public string Editors { get; set; }
        public string Pages { get; set; }
        public string LgJrName { get; set; }
        public string AbJrName { get; set; }
        public string ISSN { get; set; }
        public string Volume { get; set; }
        public string Issue { get; set; }
        public string SeriName { get; set; }
        public string SeriNo { get; set; }
        public string RprtTitle { get; set; }
        public string FileFrmt { get; set; }
        public string WWW { get; set; }
        public string Medium { get; set; }
        public string OS { get; set; }
        public string Media { get; set; }
        public string Valid { get; set; }
        public string Remarks { get; set; }
        public string FoodId { get; set; }
        public string DateUpdated { get; set; }
        public string UpdatedBy { get; set; }
        public string DocLink { get; set; }
    }
}
