//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComidaService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class shoppinglistmembers
    {
        public int ID { get; set; }
        public int ShoppingListID { get; set; }
        public int UserID { get; set; }
    
        public virtual shoppinglist shoppinglist { get; set; }
        public virtual user user { get; set; }
    }
}
