//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComidaService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class shoppinglist
    {
        public shoppinglist()
        {
            this.shoppinglistitem = new HashSet<shoppinglistitem>();
            this.shoppinglistmembers = new HashSet<shoppinglistmembers>();
        }
    
        public int ID { get; set; }
        public int UserID { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> CreationTime { get; set; }
        public Nullable<System.DateTime> DuoDate { get; set; }
        public Nullable<bool> Executed { get; set; }
    
        public virtual ICollection<shoppinglistitem> shoppinglistitem { get; set; }
        public virtual ICollection<shoppinglistmembers> shoppinglistmembers { get; set; }
        public virtual user user { get; set; }
    }
}
