//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComidaService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class useractivity
    {
        public int ID { get; set; }
        public int UserID { get; set; }
        public int ActivityID { get; set; }
        public Nullable<double> CalorieBurn { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
    
        public virtual activity activity { get; set; }
        public virtual user user { get; set; }
    }
}
