//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComidaService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class userintake
    {
        public int ID { get; set; }
        public int UserID { get; set; }
        public int ItemID { get; set; }
        public Nullable<double> ColorieBurn { get; set; }
        public Nullable<double> Amount { get; set; }
        public Nullable<System.DateTime> Time { get; set; }
    
        public virtual foodinfo foodinfo { get; set; }
        public virtual user user { get; set; }
    }
}
